import { useState, useEffect } from 'react';
import { generateStandup, getTodayStandup, saveStandup } from '../api/client';

const useStandup = ({ onSaveSuccess } = {}) => {
  const [form, setForm] = useState({ yesterday: '', today: '', blockers: '' });
  const [status, setStatus] = useState('idle');
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const [savedAt, setSavedAt] = useState(null);
  const [slackSent, setSlackSent] = useState(false);
  const [sendToSlack, setSendToSlack] = useState(false);
  const [error, setError] = useState(null);
  const [activity, setActivity] = useState(null);

  useEffect(() => {
    const loadToday = async () => {
      setStatus('loading');
      try {
        const today = await getTodayStandup();
        if (today) {
          setForm({
            yesterday: today.yesterday || '',
            today: today.today || '',
            blockers: today.blockers || '',
          });
          setIsAutoGenerated(today.auto_generated);
          setSavedAt(today.created_at);
          setStatus('saved');
        } else {
          setStatus('idle');
        }
      } catch {
        setStatus('idle');
      }
    };
    loadToday();
  }, []);

  const handleGenerate = async () => {
    setStatus('generating');
    setError(null);
    try {
      const data = await generateStandup();
      setForm({
        yesterday: data.draft.yesterday,
        today: data.draft.today,
        blockers: data.draft.blockers,
      });
      setActivity(data.activity);
      setIsAutoGenerated(true);
      setStatus('idle');
    } catch (err) {
      setError(err.error || 'Failed to generate standup');
      setStatus('error');
    }
  };

  const handleChange = (field, value) => {
    setForm((prev) => ({ ...prev, [field]: value }));
    if (status === 'saved') setStatus('idle');
  };

  const handleSave = async () => {
    setStatus('saving');
    setError(null);
    setSlackSent(false);
    try {
      const saved = await saveStandup({
        ...form,
        auto_generated: isAutoGenerated,
        send_to_slack: sendToSlack,
      });
      setSavedAt(saved.created_at);
      if (saved.slack_sent) setSlackSent(true);
      if (saved.slack_error) setError(saved.slack_error);
      setStatus('saved');

      
      if (onSaveSuccess) onSaveSuccess();
    } catch (err) {
      setError(err.error || 'Failed to save standup');
      setStatus('error');
    }
  };

  return {
    form, status, isAutoGenerated, savedAt, slackSent,
    sendToSlack, setSendToSlack, error, activity,
    handleGenerate, handleChange, handleSave,
  };
};

export default useStandup;