import { useState, useEffect } from 'react';
import {
  generateStandup,
  getTodayStandup,
  saveStandup,
} from '../api/client';

const useStandup = () => {
  const [form, setForm] = useState({
    yesterday: '',
    today: '',
    blockers: '',
  });

  const [status, setStatus] = useState('idle'); 
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const [savedAt, setSavedAt] = useState(null);
  const [error, setError] = useState(null);
  const [activity, setActivity] = useState(null);

  
  useEffect(() => {
    const loadToday = async () => {
      setStatus('loading');
      try {
        const today = await getTodayStandup();
        if (today) {
          setForm({
            yesterday: today.yesterday || '',
            today: today.today || '',
            blockers: today.blockers || '',
          });
          setIsAutoGenerated(today.auto_generated);
          setSavedAt(today.created_at);
          setStatus('saved');
        } else {
          setStatus('idle');
        }
      } catch {
        setStatus('idle');
      }
    };

    loadToday();
  }, []);

  const handleGenerate = async () => {
    setStatus('generating');
    setError(null);
    try {
      const data = await generateStandup();
      setForm({
        yesterday: data.draft.yesterday,
        today: data.draft.today,
        blockers: data.draft.blockers,
      });
      setActivity(data.activity);
      setIsAutoGenerated(true);
      setStatus('idle');
    } catch (err) {
      setError(err.error || 'Failed to generate standup');
      setStatus('error');
    }
  };

  const handleChange = (field, value) => {
    setForm((prev) => ({ ...prev, [field]: value }));
    if (status === 'saved') setStatus('idle');
  };

  const handleSave = async () => {
    setStatus('saving');
    setError(null);
    try {
      const saved = await saveStandup({
        ...form,
        auto_generated: isAutoGenerated,
      });
      setSavedAt(saved.created_at);
      setStatus('saved');
    } catch (err) {
      setError(err.error || 'Failed to save standup');
      setStatus('error');
    }
  };

  return {
    form,
    status,
    isAutoGenerated,
    savedAt,
    error,
    activity,
    handleGenerate,
    handleChange,
    handleSave,
  };
};

export default useStandup;