import { useNavigate } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth.jsx';
import useStandup from '../hooks/useStandup.js';

const fieldStyle = {
  width: '100%',
  minHeight: '120px',
  padding: '12px',
  fontSize: '14px',
  fontFamily: 'inherit',
  border: '1px solid #e2e8f0',
  borderRadius: '8px',
  resize: 'vertical',
  outline: 'none',
  boxSizing: 'border-box',
  lineHeight: '1.6',
  color: '#1a202c',
  background: '#fff',
};

const labelStyle = {
  display: 'block',
  fontSize: '13px',
  fontWeight: '500',
  color: '#4a5568',
  marginBottom: '6px',
};

const Standup = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const {
    form,
    status,
    isAutoGenerated,
    savedAt,
    error,
    activity,
    handleGenerate,
    handleChange,
    handleSave,
  } = useStandup();

  const isLoading = status === 'loading';
  const isGenerating = status === 'generating';
  const isSaving = status === 'saving';
  const isSaved = status === 'saved';

  const formatTime = (isoString) => {
    if (!isoString) return '';
    return new Date(isoString).toLocaleTimeString([], {
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const today = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  if (isLoading) {
    return (
      <div style={{ padding: '40px', textAlign: 'center', color: '#718096' }}>
        Loading today's standup...
      </div>
    );
  }

  return (
    <div style={{ maxWidth: '720px', margin: '0 auto', padding: '40px 24px' }}>

    
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '32px' }}>
        <div>
          <button
            onClick={() => navigate('/dashboard')}
            style={{ background: 'none', border: 'none', color: '#718096', cursor: 'pointer', fontSize: '13px', padding: 0, marginBottom: '8px' }}
          >
            ← Back to dashboard
          </button>
          <h1 style={{ fontSize: '22px', fontWeight: '600', color: '#1a202c', margin: 0 }}>
            Daily Standup
          </h1>
          <p style={{ fontSize: '13px', color: '#718096', margin: '4px 0 0' }}>{today}</p>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <img
            src={user?.avatar_url}
            alt={user?.username}
            style={{ width: '32px', height: '32px', borderRadius: '50%' }}
          />
          <span style={{ fontSize: '13px', color: '#4a5568' }}>{user?.username}</span>
        </div>
      </div>

     
      {isAutoGenerated && (
        <div style={{
          background: '#EBF8FF',
          border: '1px solid #BEE3F8',
          borderRadius: '8px',
          padding: '10px 14px',
          marginBottom: '24px',
          fontSize: '13px',
          color: '#2B6CB0',
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
        }}>
          <span>Auto-generated from your GitHub activity. Review and edit before saving.</span>
        </div>
      )}

    
      {error && (
        <div style={{
          background: '#FFF5F5',
          border: '1px solid #FED7D7',
          borderRadius: '8px',
          padding: '10px 14px',
          marginBottom: '24px',
          fontSize: '13px',
          color: '#C53030',
        }}>
          {error}
        </div>
      )}

      {/* Form */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>

        <div>
          <label style={labelStyle}>What did you do yesterday?</label>
          <textarea
            style={fieldStyle}
            value={form.yesterday}
            onChange={(e) => handleChange('yesterday', e.target.value)}
            placeholder="• Worked on auth flow&#10;• Reviewed 2 PRs"
          />
        </div>

        <div>
          <label style={labelStyle}>What will you do today?</label>
          <textarea
            style={fieldStyle}
            value={form.today}
            onChange={(e) => handleChange('today', e.target.value)}
            placeholder="• Finish the standup generator&#10;• Deploy to staging"
          />
        </div>

        <div>
          <label style={labelStyle}>Any blockers?</label>
          <textarea
            style={{ ...fieldStyle, minHeight: '80px' }}
            value={form.blockers}
            onChange={(e) => handleChange('blockers', e.target.value)}
            placeholder="None"
          />
        </div>

      </div>

   
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '28px' }}>

        <button
          onClick={handleGenerate}
          disabled={isGenerating || isSaving}
          style={{
            padding: '9px 16px',
            fontSize: '13px',
            fontWeight: '500',
            background: 'none',
            border: '1px solid #e2e8f0',
            borderRadius: '8px',
            cursor: isGenerating ? 'not-allowed' : 'pointer',
            color: '#4a5568',
            opacity: isGenerating ? 0.6 : 1,
          }}
        >
          {isGenerating ? 'Generating...' : 'Generate from GitHub'}
        </button>

        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          {isSaved && savedAt && (
            <span style={{ fontSize: '12px', color: '#48BB78' }}>
              Saved at {formatTime(savedAt)}
            </span>
          )}
          <button
            onClick={handleSave}
            disabled={isSaving || isGenerating || (!form.yesterday && !form.today)}
            style={{
              padding: '9px 20px',
              fontSize: '13px',
              fontWeight: '500',
              background: '#3182CE',
              color: '#fff',
              border: 'none',
              borderRadius: '8px',
              cursor: isSaving ? 'not-allowed' : 'pointer',
              opacity: isSaving ? 0.7 : 1,
            }}
          >
            {isSaving ? 'Saving...' : isSaved ? 'Update' : 'Save standup'}
          </button>
        </div>

      </div>

      {activity && (
        <div style={{ marginTop: '40px', borderTop: '1px solid #e2e8f0', paddingTop: '28px' }}>
          <h3 style={{ fontSize: '14px', fontWeight: '600', color: '#2d3748', marginBottom: '16px' }}>
            GitHub activity used to generate this
          </h3>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '12px' }}>

            <ActivityCard
              title="Commits"
              count={activity.commits.length}
              items={activity.commits.map((c) => `${c.repo.split('/')[1]}: ${c.message}`)}
            />

            <ActivityCard
              title="Pull requests"
              count={activity.prs.length}
              items={activity.prs.map((p) => p.title)}
            />

            <ActivityCard
              title="Reviews"
              count={activity.reviews.length}
              items={activity.reviews.map((r) => r.title)}
            />

          </div>
        </div>
      )}

    </div>
  );
};

const ActivityCard = ({ title, count, items }) => (
  <div style={{
    background: '#F7FAFC',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    padding: '12px',
  }}>
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
      <span style={{ fontSize: '12px', fontWeight: '600', color: '#4a5568' }}>{title}</span>
      <span style={{ fontSize: '11px', background: '#e2e8f0', color: '#718096', padding: '1px 7px', borderRadius: '99px' }}>
        {count}
      </span>
    </div>
    {items.length === 0 ? (
      <p style={{ fontSize: '12px', color: '#a0aec0', margin: 0 }}>None found</p>
    ) : (
      items.slice(0, 3).map((item, i) => (
        <p key={i} style={{ fontSize: '12px', color: '#718096', margin: '0 0 4px', lineHeight: '1.4',
          overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
          {item}
        </p>
      ))
    )}
  </div>
);

export default Standup;