const db = require('./index');

const getUsersByIds = async (ids) => {
  const { rows } = await db.query(
    'SELECT id, username, avatar_url, slack_webhook_url FROM users WHERE id = ANY($1)',
    [ids]
  );
  return rows;
};


const upsertStandup = async (userId, yesterday, today, blockers, autoGenerated) => {
  const { rows } = await db.query(
    `INSERT INTO standups (user_id, yesterday, today, blockers, auto_generated)
     VALUES ($1, $2, $3, $4, $5)
     ON CONFLICT (user_id, date)
     DO UPDATE SET yesterday = $2, today = $3, blockers = $4
     RETURNING id, date, yesterday, today, blockers, auto_generated, created_at`,
    [userId, yesterday, today, blockers, autoGenerated]
  );
  return rows[0];
};

const getStandupHistory = async (userId, limit = 30, offset = 0) => {
  const { rows } = await db.query(
    `SELECT id, date, yesterday, today, blockers, auto_generated, created_at
     FROM standups
     WHERE user_id = $1
     ORDER BY date DESC
     LIMIT $2 OFFSET $3`,
    [userId, limit, offset]
  );
  return rows;
};

module.exports = { getUsersByIds, upsertStandup, getStandupHistory };